import { IPost } from "../interfaces/Post";

export const uniquePostMock: IPost = {
  postId: "1234",
  author: "John Dow",
  storyTitle: "Story of my life",
  storyUrl: "https://www.google.com/",
  createdAt: new Date("2023-03-15T17:10:35.961Z"),
  isLiked: false,
  framework: "angular",
};

export const multiplePostsMock: IPost[] = [
  {
    postId: "12341",
    author: "John Dow",
    storyTitle: "Story of my life",
    storyUrl: "https://www.google.com/",
    createdAt: new Date("2023-03-15T17:10:35.961Z"),
    isLiked: false,
    framework: "angular",
  },
  {
    postId: "12342",
    author: "John Dow",
    storyTitle: "Story of my life",
    storyUrl: "https://www.google.com/",
    createdAt: new Date("2023-03-15T17:10:35.961Z"),
    isLiked: false,
    framework: "angular",
  },
  {
    postId: "12343",
    author: "John Dow",
    storyTitle: "Story of my life",
    storyUrl: "https://www.google.com/",
    createdAt: new Date("2023-03-15T17:10:35.961Z"),
    isLiked: false,
    framework: "angular",
  },
  {
    postId: "12344",
    author: "John Dow",
    storyTitle: "Story of my life",
    storyUrl: "https://www.google.com/",
    createdAt: new Date("2023-03-15T17:10:35.961Z"),
    isLiked: false,
    framework: "angular",
  },
  {
    postId: "12345",
    author: "John Dow",
    storyTitle: "Story of my life",
    storyUrl: "https://www.google.com/",
    createdAt: new Date("2023-03-15T17:10:35.961Z"),
    isLiked: false,
    framework: "angular",
  },
  {
    postId: "12346",
    author: "John Dow",
    storyTitle: "Story of my life",
    storyUrl: "https://www.google.com/",
    createdAt: new Date("2023-03-15T17:10:35.961Z"),
    isLiked: false,
    framework: "angular",
  },
  {
    postId: "12347",
    author: "John Dow",
    storyTitle: "Story of my life",
    storyUrl: "https://www.google.com/",
    createdAt: new Date("2023-03-15T17:10:35.961Z"),
    isLiked: false,
    framework: "angular",
  },
  {
    postId: "12348",
    author: "John Dow",
    storyTitle: "Story of my life",
    storyUrl: "https://www.google.com/",
    createdAt: new Date("2023-03-15T17:10:35.961Z"),
    isLiked: false,
    framework: "angular",
  },
];
